version: '3.7'
services:
  dockersql1:
    restart: on-failure
    container_name: dockersql1
    hostname: dockersql1
    build:
      context: .
      dockerfile: dockerfile
      args:
        PRIMARYSQL: "TRUE"
        IMAGE: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "1433:1433"
    env_file:
      - sql/sqlserver.env
      - sql/sapassword.env
  dockersql2:
    restart: on-failure
    container_name: dockersql2
    hostname: dockersql2
    build:
      context: .
      dockerfile: dockerfile
      args:
        IMAGE: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "14333:1433"
    env_file:
      - sql/sqlserver.env
      - sql/sapassword.env
