version: '3.7'
services:
  dockersql1:
    container_name: sqltest1
    hostname: sqltest1
    build:
      context: .
      dockerfile: dockerfile
      args:
        PRIMARYSQL: "TRUE"
    ports:
      - "1433:1433"
    env_file:
      - sql/sqlserver.env
      - sql/sapassword.env
  dockersql2:
    container_name: sqltest2
    hostname: sqltest2
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "14333:1433"
    env_file:
      - sql/sqlserver.env
      - sql/sapassword.env
