version: '3.7'
services:
  mssql1:
    restart: on-failure
    networks:
      - localnet
    container_name: mssql1
    hostname: mssql1
    image: dbatools/sqlinstance:latest-amd64
    build:
      context: .
      dockerfile: dockerfile
      args:
        PRIMARYSQL: "TRUE"
        IMAGE: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    env_file:
      - sql/sapassword.env
    volumes:
      - shared:/shared:z
  mssql2:
    restart: on-failure
    networks:
      - localnet
    container_name: mssql2
    hostname: mssql2
    image: dbatools/sqlinstance2:latest-amd64
    build:
      context: .
      dockerfile: dockerfile
      args:
        IMAGE: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "14333:1433"
    env_file:
      - sql/sapassword.env
    volumes:
      - shared:/shared:z

networks:
  localnet: null
volumes:
  shared: null
