version: '3.7'
services:
  dockersql1:
    container_name: dockersql1
    hostname: dockersql1
    build:
      context: .
      dockerfile: dockerfile
      args:
        PRIMARYSQL: "TRUE"
    ports:
      - "1433:1433"
    env_file:
      - sql/sqlserver.env
      - sql/sapassword.env
    networks:
      - localnet
  dockersql2:
    container_name: dockersql2
    hostname: dockersql2
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "14333:1433"
    env_file:
      - sql/sqlserver.env
      - sql/sapassword.env
    networks:
      - localnet
networks:
  localnet: null
