name: Deploy mssqlbase images to Docker
on:
  workflow_dispatch:

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Can't be all in one step bc it uses
      # two entirely different images
      - name: Build ARM64 and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: "./sqlinstance/arch/arm64"
          platforms: linux/arm64
          push: true
          tags: |
            dbatools/mssqlbase:latest-arm64

      - name: Build AMD64 and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: "./sqlinstance/arch/amd64"
          platforms: linux/amd64
          push: true
          tags: |
            dbatools/mssqlbase:latest-amd64

      - name: Create and push manifest
        run: |
          docker manifest create dbatools/mssqlbase:latest --amend dbatools/mssqlbase:latest-amd64 --amend dbatools/mssqlbase:latest-arm64
          docker manifest push docker.io/dbatools/mssqlbase:latest --purge
