name: Test self-hosted
on:
  push:
    branches:
      - self
jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build docker images
        run: docker compose -f ./sqlinstance/docker-compose.yml up --force-recreate --build --remove-orphans -d

      - name: Stop newly built containers and remove volumes
        run: docker compose -f ./sqlinstance/docker-compose.yml down --volumes

      - name: Cleanup runner
        run: |
          mv /Users/runneradmin/Documents/gha-runner-osx-arm64/_layout/_work/_actions /Users/runneradmin/Documents/gha-runner-osx-arm64/_layout/
          rm -rf /Users/runneradmin/Documents/gha-runner-osx-arm64/_layout/_work 
          mkdir /Users/runneradmin/Documents/gha-runner-osx-arm64/_layout/_work
          mv /Users/runneradmin/Documents/gha-runner-osx-arm64/_layout/_work/_actions /Users/runneradmin/Documents/gha-runner-osx-arm64/_layout/_work/
          docker volume prune -f
          docker image prune -f
          docker builder prune -a -f
