name: Build and test
on: [push]
defaults:
  run:
    shell: pwsh
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker compose -f ./sqlinstance/docker-compose.yml up --force-recreate --build --remove-orphans -d

      - name: Bring em back down
        run: docker compose down --volumes

      - name: Fire em up
        run: |
          # create a shared network
          docker network create localnet

          # Expose engine then setup a shared path for migrations
          docker run -p 1433:1433 --volume shared:/shared:z --hostname mssql1 --name mssql1 --network localnet -d dbatools/sqlinstance:latest-amd64

          # Expose second engine on different port and use the same shared path
          docker run -p 14333:1433 --volume shared:/shared:z --hostname mssql2 --name mssql2 --network localnet -d dbatools/sqlinstance2:latest-amd64

      - name: Install and cache dbatools
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: dbatools

      - name: Run tests
        run: $null = Invoke-Pester ./tests/actions.ps1 -Output Detailed -PassThru
